# Generated by Django 3.0.7 on 2020-06-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
        migrations.RenameField(
            model_name='data',
            old_name='expire',
            new_name='expire_in',
        ),
    ]
